import { AppShell } from "../../../../src/components/shared/AppShell";
import { PageHeader } from "../../../../src/components/shared/PageHeader";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "../../../../src/components/ui/Card";
import { Button } from "../../../../src/components/ui/Button";
import { Input } from "../../../../src/components/ui/Input";
import { Badge } from "../../../../src/components/ui/Badge";
import Link from "next/link";

export default function SecurityPage() {
  return (
    <AppShell>
      <div className="max-w-4xl mx-auto">
        <div className="flex items-center gap-4 mb-6">
          <Link href="/settings" className="text-muted hover:text-foreground">
            <svg className="w-5 h-5 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
          </Link>
          <PageHeader 
            title="Security & MFA" 
            description="Secure your ReviewPath account with Multi-Factor Authentication."
          />
        </div>
        
        <div className="grid gap-8">
          <Card className="border-accent/30 shadow-md">
            <CardHeader>
              <div className="flex justify-between items-center">
                <div>
                  <CardTitle className="flex items-center gap-2">
                    <svg className="w-5 h-5 text-accent" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8V7z" /></svg>
                    Two-Factor Authentication (2FA)
                  </CardTitle>
                  <CardDescription className="mt-1 flex items-center">Add an extra layer of security to your account.</CardDescription>
                </div>
                <Badge variant="outline" className="opacity-70">Not configured</Badge>
              </div>
            </CardHeader>
            <CardContent>
              <div className="flex flex-col md:flex-row gap-8 items-start mt-4 bg-panel-alt p-6 rounded-xl border border-border">
                <div className="w-48 h-48 bg-white p-2 rounded-lg shrink-0 mx-auto md:mx-0 flex items-center justify-center border-4 border-border">
                  {/* Mock QR Code Pattern using SVG */}
                  <svg viewBox="0 0 100 100" className="w-full h-full" fill="black">
                    <path d="M0 0h30v30H0zM10 10h10v10H10zM70 0h30v30H70zM80 10h10v10H80zM0 70h30v30H0zM10 80h10v10H10zM40 0h20v20H40zM40 30h10v20H40zM60 30h10v10H60zM40 60h20v10H40zM70 40h30v20H70zM40 80h20v20H40zM70 70h10v10H70zM80 90h20v10H80z" />
                  </svg>
                </div>
                <div className="flex-1 space-y-4">
                  <div>
                    <h3 className="font-semibold text-foreground mb-2">1. Scan the QR Code</h3>
                    <p className="text-sm text-muted">Use an authenticator app like Google Authenticator, Authy, or 1Password to scan this QR code.</p>
                  </div>
                  <div>
                    <h3 className="font-semibold text-foreground mb-1">2. Enter Verification Code</h3>
                    <p className="text-sm text-muted mb-3">Please enter the 6-digit code generated by your app to verify the setup.</p>
                    <div className="flex flex-wrap gap-3 max-w-xs">
                      <Input placeholder="000000" className="font-mono tracking-[0.5em] text-center text-lg w-full sm:w-auto" maxLength={6} />
                      <Button variant="primary">Verify</Button>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader>
              <CardTitle>Recovery Codes</CardTitle>
              <CardDescription>Save these in a secure place like a password manager.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="bg-panel px-6 py-8 rounded-lg border border-border border-dashed text-center">
                 <svg className="w-8 h-8 text-muted mx-auto mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 11V7a4 4 0 118 0m-4 8v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2z" /></svg>
                 <p className="text-foreground font-medium mb-1">Generate Recovery Codes</p>
                 <p className="text-sm text-muted mb-4 max-w-sm mx-auto">Enable 2FA first to generate recovery codes. These can be used to access your account if you lose your device.</p>
                 <Button variant="secondary" disabled>Generate Codes</Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </AppShell>
  );
}
